#!/usr/bin/env python3
"""
Generate a Goose SQL migration that seeds the ny_boundary table with the
union of all New York county polygons from click_that_hood.

Source GeoJSON:
  https://github.com/codeforgermany/click_that_hood/blob/main/public/data/new-york-counties.geojson

Output:
  ../internal/migrate/migrations/005_seed_ny_boundary.sql

The ny_boundary table holds a single MultiPolygon representing the full NY
state extent (including coastal/water zones).  It is used as the first-pass
gate before attempting county-level tax lookup:

  - Point outside ny_boundary  → error (not in NY state)
  - Point inside ny_boundary, but no county match → duty-free zone (tax = 0)
  - Point inside ny_boundary and inside a county → normal tax

Run from any directory — paths are relative to this file.
"""

import json
import os
import sys
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MIGRATIONS_DIR = os.path.join(SCRIPT_DIR, "..", "internal", "migrate", "migrations")

GEOJSON_URL = (
    "https://raw.githubusercontent.com/codeforgermany/click_that_hood"
    "/main/public/data/new-york-counties.geojson"
)

OUTPUT_FILE = "005_seed_ny_boundary.sql"


def fetch_geojson(url: str) -> dict:
    print(f"Downloading GeoJSON from {url} ...")
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    print(f"  Downloaded {len(data.get('features', []))} features")
    return data


def sql_str(s: str) -> str:
    """Escape a string for a SQL single-quoted literal."""
    return s.replace("'", "''")


def generate_migration(collection: dict) -> str:
    features = collection.get("features", [])
    if not features:
        raise ValueError("GeoJSON contains no features")

    # Build a VALUES list of one geometry per county.
    # We pass each county as a GeoJSON string to ST_GeomFromGeoJSON, then
    # union them all into a single MultiPolygon representing NY state.
    value_rows = []
    for feature in features:
        geom_json = json.dumps(feature["geometry"], separators=(",", ":"))
        # ST_MakeValid fixes self-intersections / precision issues that would
        # cause ST_Union to fail with a TopologyException.
        value_rows.append(
            f"        (ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON('{sql_str(geom_json)}'), 4326)))"
        )

    values_block = ",\n".join(value_rows)

    lines = [
        "-- +goose Up",
        "-- NY state boundary: union of all county polygons from click_that_hood.",
        "-- Used as the first-pass gate: points outside this polygon are rejected",
        "-- before county-level tax lookup is attempted.",
        "-- Generated by backend/scripts/gen_ny_boundary.py — do not edit by hand.",
        "",
        "CREATE TABLE IF NOT EXISTS ny_boundary (",
        "    id   SERIAL PRIMARY KEY,",
        "    geom GEOMETRY(MultiPolygon, 4326) NOT NULL",
        ");",
        "CREATE INDEX IF NOT EXISTS idx_ny_boundary_geom ON ny_boundary USING GIST(geom);",
        "",
        "INSERT INTO ny_boundary (geom)",
        "SELECT ST_Multi(ST_Union(geom)) FROM (",
        "    VALUES",
        values_block,
        ") AS t(geom);",
        "",
        "-- +goose Down",
        "DROP TABLE IF EXISTS ny_boundary;",
    ]
    return "\n".join(lines) + "\n"


def main():
    os.makedirs(MIGRATIONS_DIR, exist_ok=True)

    collection = fetch_geojson(GEOJSON_URL)

    print("Generating migration SQL ...")
    sql = generate_migration(collection)

    out_path = os.path.join(MIGRATIONS_DIR, OUTPUT_FILE)
    with open(out_path, "w") as f:
        f.write(sql)

    print(f"  Written to {out_path}")
    print("Done.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
