apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- backend.yaml
- frontend.yaml
- ingress.yaml
- postgres.yaml
- redis.yaml
images:
- name: ghcr.io/chivta/wellness-kit-backend
  newName: ghcr.io/chivta/wellness-kit-backend
  newTag: sha-624f94b
- name: ghcr.io/chivta/wellness-kit-frontend
  newName: ghcr.io/chivta/wellness-kit-frontend
  newTag: sha-624f94b
