// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Authenticate with email and password to receive access and refresh tokens",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Login with credentials",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {"type": "string"},
                                "password": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token pair",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {"type": "string"},
                                "refresh_token": {"type": "string"},
                                "expires_in": {"type": "integer"}
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new access + refresh token pair",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New token pair",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {"type": "string"},
                                "refresh_token": {"type": "string"},
                                "expires_in": {"type": "integer"}
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "Invalidate a refresh token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh token to invalidate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Logged out"}
                }
            }
        },
        "/api/auth/google": {
            "get": {
                "description": "Redirects the user to Google OAuth2 consent screen",
                "tags": ["auth"],
                "summary": "Initiate Google OAuth login",
                "responses": {
                    "302": {"description": "Redirect to Google"}
                }
            }
        },
        "/api/auth/google/callback": {
            "get": {
                "description": "Handles the OAuth2 callback from Google, creates/finds user, issues tokens",
                "tags": ["auth"],
                "summary": "Google OAuth callback",
                "parameters": [
                    {"name": "code", "in": "query", "type": "string", "required": true},
                    {"name": "state", "in": "query", "type": "string"}
                ],
                "responses": {
                    "302": {"description": "Redirect to frontend with tokens"}
                }
            }
        },
        "/api/orders/import": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Upload a CSV file with order data. The system parses, calculates taxes, and saves all orders.",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "tags": ["orders"],
                "summary": "Import orders from CSV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file with orders",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Import result",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "total_imported": {"type": "integer"},
                                "total_failed": {"type": "integer"},
                                "total_tax": {"type": "number"},
                                "errors": {"type": "array", "items": {"type": "string"}}
                            }
                        }
                    }
                }
            }
        },
        "/api/orders": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns paginated orders with calculated tax data. Supports filtering.",
                "produces": ["application/json"],
                "tags": ["orders"],
                "summary": "List orders with pagination and filters",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "page_size", "in": "query", "type": "integer", "default": 20},
                    {"name": "county", "in": "query", "type": "string"},
                    {"name": "date_from", "in": "query", "type": "string"},
                    {"name": "date_to", "in": "query", "type": "string"},
                    {"name": "min_total", "in": "query", "type": "number"},
                    {"name": "max_total", "in": "query", "type": "number"}
                ],
                "responses": {
                    "200": {
                        "description": "Orders response",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "orders": {"type": "array", "items": {"$ref": "#/definitions/Order"}},
                                "total": {"type": "integer"},
                                "page": {"type": "integer"},
                                "page_size": {"type": "integer"},
                                "total_pages": {"type": "integer"}
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Create an order manually with lat, lon, subtotal. Tax is calculated immediately.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["orders"],
                "summary": "Create a single order",
                "parameters": [
                    {
                        "description": "Order data",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "latitude": {"type": "number"},
                                "longitude": {"type": "number"},
                                "subtotal": {"type": "number"},
                                "timestamp": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created order",
                        "schema": {"$ref": "#/definitions/Order"}
                    }
                }
            }
        }
    },
    "definitions": {
        "Order": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "external_id": {"type": "integer"},
                "latitude": {"type": "number"},
                "longitude": {"type": "number"},
                "subtotal": {"type": "number"},
                "timestamp": {"type": "string"},
                "county_fips": {"type": "string"},
                "county_name": {"type": "string"},
                "state_rate": {"type": "number"},
                "county_rate": {"type": "number"},
                "city_rate": {"type": "number"},
                "special_rate": {"type": "number"},
                "composite_tax_rate": {"type": "number"},
                "tax_amount": {"type": "number"},
                "total_amount": {"type": "number"},
                "created_at": {"type": "string"}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your bearer token: Bearer \u003ctoken\u003e"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Instant Wellness Tax Calculator API",
	Description:      "API for calculating NY State composite sales tax on drone-delivered wellness kit orders.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
